---
- name: Create new IAM user with API keys
  iam:
    iam_type: user
    name: "{{iam_user_name}}"
    state: present
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    password: "{{iam_password}}"
    access_key_state: create
    groups: "{{iam_group}}"
 